#!/usr/bin/env bash

cd "$(git rev-parse --show-toplevel)"

files=()
while IFS= read -r -d '' file; do
    files+=("$file")
done < <(git diff --cached --name-only --diff-filter=A -z)

if (( ${#files[@]} == 0 )); then
    exit 0
fi

bash scripts/addlicense.sh "${files[@]}"
git add -- "${files[@]}"
